x-uid: &uid ${UID:-999}
x-gid: &gid ${GID:-1000}

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: *uid
        GID: *gid
    user: "${UID:-999}:${GID:-1000}"
    restart: unless-stopped
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:80"
    depends_on:
      - backend
